EventRegistrationSystem/Controllers/EventsController.cs
using EventRegistrationSystem.Models;
using EventRegistrationSystem.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EventRegistrationSystem.Controllers
{
    public class EventsController : Controller
    {
        private readonly IEvent _context;
        public EventsController(IEvent context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> GetEvents(string searchString)
        {
            var allEvents = _context.GetAllEvent();
            return View(allEvents);
        }

        [HttpGet]
        public IActionResult AddEvent()
        {
            Event even = new Event();
            return View(even);
        }

        [HttpPost]
        public async Task<IActionResult> AddEvent(Event events)
        {
            _context.CreateEvent(events);
            return RedirectToAction("GetEvents");
        }

        [HttpGet]
        public async Task<IActionResult> GetEventById(int id)
        {
            var getById = _context.GetEvent(id);
            return View(getById);
        }

        [HttpGet]
        public async Task<IActionResult> EditEvent(int id)
        {
            Event even = new Event();
            return View(even);
        }

        [HttpPost]
        public async Task<IActionResult> EditEvent(int id, Event events)
        {
            _context.UpdateEvent(events);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteEvent(int id)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteEventConfirmed(int id)
        {
            _context.DeleteEvent(id);
            return RedirectToAction("Index");
        }
    }
}

EventRegistrationSystem/Controllers/RegistraionsController.cs
using EventRegistrationSystem.Data;
using EventRegistrationSystem.Models;
using EventRegistrationSystem.Repository.Serveses;
using Mailjet.Client.Resources;
using Microsoft.AspNetCore.Mvc;

namespace EventRegistrationSystem.Controllers
{
    public class RegistraionsController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly RegistrationDBContext _context;

        public RegistraionsController(IConfiguration configuration, RegistrationDBContext context)
        {
            _configuration = configuration;
            _context = context;
        }

        public IActionResult Index()
        {
            // Fetch registrations from the database and pass them to the view
            var registrations = _context.registrations.ToList();
            return View(registrations);
        }

        [HttpPost]
        public IActionResult Index(int registrationId)
        {
            // Find the registration based on the provided registrationId
            var registration = _context.registrations.Where(a => a.RegistrationId == registrationId).First();

            if (registration != null)
            {
                // Create an instance of MailjetService and send the email
                EmailService service = new EmailService(_configuration);
                service.SendEmailAsync(
                     registration.Email,
                     registration.ParticipantName,
                     "<h1>Your registration has been approved!</h1>");
            }

            return RedirectToAction("Index");
        }
        public IActionResult Create()
        {
            Registration regester = new Registration();
            return View(regester);
        }
        [HttpPost]
        public IActionResult Create(Registration registration)
        {
            var regester = new Registration()
            {
                RegistrationId = registration.RegistrationId,
                Email = registration.Email,
                ParticipantName = registration.ParticipantName,
                EventId = registration.EventId,
                UserId = registration.UserId
            };
            _context.registrations.Add(regester);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

EventRegistrationSystem/Controllers/UserController.cs
using EventRegistrationSystem.Data;
using EventRegistrationSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EventRegistrationSystem.Controllers
{
    public class UserController : Controller
    {
        private readonly RegistrationDBContext _context;

        public UserController(RegistrationDBContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetUsers(string searchString)
        {
            var result = _context.users.ToList();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetUserById(string id)
        {
            var book = await _context.users.FindAsync(id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var book = await _context.users.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(string id, User book)
        {
            var existingBook = await _context.users.FindAsync(id);
            if (existingBook == null)
            {
                return NotFound();
            }

            // Update book properties
            existingBook.Email = book.Email;
            existingBook.UserName = book.UserName;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return StatusCode(500, "Error updating the user. Please try again later.");
            }

            return RedirectToAction("GetUsers");
        }
        [HttpGet]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var book = await _context.users.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book); // Show the book details to confirm deletion
        }
        [HttpPost]
        public async Task<IActionResult> DeleteUserConfirmed(string id)
        {
            var book = await _context.users.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            _context.users.Remove(book);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(GetUsers));
        }
    }
}

EventRegistrationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventRegistrationSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventRegistrationSystem.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventRegistrationSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetUsers">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="GetEvents">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registraions" asp-action="Create">Registraions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EventRegistrationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>